---
title: "Compare Model Configurations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Compare Model Configurations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, include = FALSE, warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  fig.width = 6, fig.height = 5, 
  warning = FALSE
  )
```


```{r setup}
library(ggplot2)  # package used to visualize results 
library(knitr)    # makes nice tables
library(magrittr) # import the %>% pipeline

library(MEMC)     # MEMC should already be installed, see installation instructions. 

theme_set(theme_bw())  # set a theme to use in all the plots
```


In this example we will compare there default model configurations included with the package `MEND_model`, `COMISSION_model`, 
`CORPSE_model`.

```{r}
time <- seq(from = 1, to = 3000, by = 10)
mend_out <- solve_model(MEND_model, time = time, params = default_params, state = default_initial)
comiss_out <- solve_model(COMISSION_model, time = time, params = default_params, state = default_initial)
corpse_out <- solve_model(CORPSE_model, time = time, params = default_params, state = default_initial)

out <- rbind(mend_out, comiss_out, corpse_out)
```

Visualize the outputs. 

```{r}
out %>% 
  ggplot(aes(time, value, color = name)) + 
  geom_line() + 
  facet_wrap("variable", scales = "free") + 
  labs(title = "Model Configurations", y = unique(out$units)) + 
  facet_wrap("variable", scales = "free") + 
  theme(legend.title = element_blank())
```

How do the different model configurations compare with one another? Take a look at the model configuration tables, this will tell us what kinetics model were used where.


```{r}
knitr::kable(rbind(MEND_model$config, COMISSION_model$config, CORPSE_model$config))
```
