# Check to see if development has resulted in changes in the output. When we see an expected change in the model output
# the comparison data will have to be regenerated by running data-raw/compdata.R


# Read in the archived comparison data.
old <- read.csv('compdata.csv')

# the time to solve the model for
t <- unique(old$time)

# our testing definition of 0
zero_threshold <- 1e-9

# Calculate the total error between the old and new data
#
# Note error is the old - new
#
# Args
#  old: data frame of the old model output data to do the comparison with
#  new: data frame of the new data output
# Return: data frame of the total error between the values returned for the variable
old_new_compare <- function(old, new){
  compdf <- data.table::as.data.table(merge(old, new, by = c("time", "variable", "units", "name")))
  compdf$error <- (compdf$old_value - compdf$value)

  split(compdf, compdf$variable) %>%
    lapply(function(df){
      data.frame(variable = unique(df[["variable"]]), error = sum(df[['error']]))
    }) %>%
    do.call(what = "rbind") ->
    out

  return(out)
}


test_that("MEND_model old new", {

  out <- solve_model(mod = MEND_model, time = t)
  old <- old[old["name"] == "MEND", ]
  compdf <- old_new_compare(old, out)
  expect_true(all(abs(compdf$error) <= zero_threshold))

})

test_that("COMISSION_model old new", {

  out <- solve_model(mod = COMISSION_model, time = t)
  old <- old[old["name"] == "COMISSION", ]
  compdf <- old_new_compare(old, out)
  expect_true(all(abs(compdf$error) <= zero_threshold))

})

test_that("CORPSE_model old new", {

  out <- solve_model(mod = CORPSE_model, time = t)
  old <- old[old["name"] == "CORPSE", ]
  compdf <- old_new_compare(old, out)
  expect_true(all(abs(compdf$error) <= zero_threshold))

})
