---
title: "Fit Data"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# Load the package
library(MEMC)

# Load other R package that will use 
library(FME)
library(ggplot2)
library(data.table) # Helps format the data 
```


Load the example observations and the initial state values. 

```{r, warning=FALSE, message=FALSE}
# The observations
obs <- read.csv(system.file("example/exmaple_data.csv", package = "MEMC"))

# Load the initial state values and format them as a list. 
obs_initial_val_data <- read.csv(system.file("example/exmaple_initial.csv", package = "MEMC"))
obs_initial_values <- obs_initial_val_data$value
names(obs_initial_values) <- obs_initial_val_data$state
```


```{r}
mod1 <- configure_model(params = default_params, state = initial_values, name = "MEND")
objective1 <- make_objective_function(obs = obs, config = mod1)

objective1
objective1(c(V.d = 2, V.p = 25, V.m = 0.4))

fit1 <- modFit(f = objective1, p = c(V.d = 2, V.p = 25, V.m = 0.4), lower = c(0, 0, 0))
```

```{r}
mod2 <- COMISSION_model
mod2$state <- Ultisol_state
objective2 <- make_objective_function(obs = obs, config = mod2)
fit2 <- modFit(f = objective2, p = fit1$par, lower = c(0, 0, 0))
```

```{r}
mod3 <- CORPSE_model
mod3$state <- Ultisol_state
objective3 <- make_objective_function(obs = obs, config = mod3)
fit3 <- modFit(f = objective3, p = c(V.d = 10, V.p = 10, V.m = 10), lower = c(0, 0, 0))
```
