#' Helper function that quickly visualizes results returned by memc_solve, memc_sensfunc, or memc_sensrange
#'
#' @param obj object to plot, data frame returned by memc_solve or the object created by memc_sensfunc, or memc_sensrange
#' @return a ggplot2 plot
#' @importFrom assertthat assert_that has_args
#' @export
#' @import ggplot2
memc_plot <- function(obj) {
  # Silence package checks
  time <- value <- name <- Mean <- Min <- Max <-
    parameter <- NULL
  # Check that is one of the supported plotting types
  assert_that(any(class(obj) %in% c("data.frame", "sensFun", "sensRange")))
  
  # If the object was generated from memc_solve then make
  # a traditional line plot
  if (all(class(obj) == list("data.table", "data.frame"))) {
    
    # Save a copy of the units
    units <- unique(obj$units)
    
    # Make a line plot for the different soil carbon pools
    ggplot(data = obj) +
      geom_line(aes(time, value, color = name)) +
      facet_wrap("variable", scales = "free") +
      labs(x = "Time (days)", y = units) +
      scale_color_manual(values = memc_colorPalette()) +
      theme_bw() +
      theme(legend.title = element_blank()) ->
      plot
    
  }
  
  
  # If the object read in was generated by memc_sensrange
  if (all(class(obj) == list("sensRange", "data.frame"))) {
    to_plot <- memc_format_sensout(obj)
    
    ggplot(data = to_plot) +
      geom_line(aes(time, Mean)) +
      geom_ribbon(aes(time, ymin = Min, ymax = Max), alpha = 0.5) +
      facet_wrap("variable", scales = "free") +
      theme_bw() +
      labs(x = "Time (days)", y = NULL) ->
      plot
  }
  
  # If the object read in was generated by memc_sensfun
  if (all(class(obj) == list("sensFun", "data.frame"))) {
    to_plot <- memc_format_sensout(obj)
    
    ggplot(data = to_plot) +
      geom_line(aes(time, value, color = parameter)) +
      facet_wrap("variable", scales = "free") +
      labs(x = "Time (days)", y = "Difference in Output") +
      theme_bw() +
      theme(legend.title = element_blank()) ->
      plot
  }
  
  return(plot)
  
}
