env:
    cache-version: v1
    r-version: 3.6

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test-coverage

jobs:
  test-coverage:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          r-version: ${{ env.r-version }}

      - uses: r-lib/actions/setup-r@master

      - name: Query dependencies
        run: |
          install.packages(c('remotes', 'ggplot2', 'deSolve', 'mcmc'))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ env.cache-version }}-macOS-r-${{ env.r-version }}-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ env.cache-version }}-macOS-r-${{ env.r-version }}-

      - name: Install dependencies
        run: |
          install.packages(c("remotes", 'ggplot2', 'deSolve', 'mcmc'))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
